<a href="https://colab.research.google.com/github/C4st3ll4n/q-learning/blob/main/qlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importação de libs

In [1]:
import numpy as np


Definindo constantes

In [2]:
gamma = .75
alpha =  .9


Configurando ambiente

In [3]:
location_to_state = {"A":0,"B":1,"C":2,"D":3,"E":4,"F":5,"G":6,"H":7,"I":8,"J":9,"K":10,"L":11}
state_to_location = {state:location for location, state in location_to_state.items()}

actions = [0,1,2,3,4,5,6,7,8,9,10,11]
R = np.array([
              [0,1,0,0,0,0,0,0,0,0,0,0],
              [1,0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,1,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,0],
              [0,1,0,0,0,0,0,0,0,1,0,0],
              [0,0,1,0,0,0,1000,1,0,0,0,0],
              [0,0,0,1,0,0,1,0,0,0,0,1],
              [0,0,0,0,1,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0,1,0,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1],
              [0,0,0,0,0,0,0,1,0,0,1,0],
              ])

In [4]:
Q = np.array(np.zeros([12,12]))

In [5]:
for i in range(2000):
    current_state = np.random.randint(0,12)
    
    ### Check the actions that the agent can do and append in a list
    playable_actions = []
    for j in range(12):
        if R[current_state, j] > 0:
            playable_actions.append(j)

    next_state = np.random.choice(playable_actions)

    time_difference = R[current_state, next_state] + gamma *\
     Q[next_state, np.argmax(Q[next_state,])] - Q[current_state, next_state]

    Q[current_state, next_state] = Q[current_state, next_state] + alpha\
     * time_difference

     



In [6]:
print(Q.astype(int))

[[   0 1689    0    0    0    0    0    0    0    0    0    0]
 [1268    0 2251    0    0 1268    0    0    0    0    0    0]
 [   0 1689    0    0    0    0 3000    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2251    0    0    0    0]
 [   0    0    0    0    0    0    0    0  715    0    0    0]
 [   0 1689    0    0    0    0    0    0    0  952    0    0]
 [   0    0 2251    0    0    0 3999 2251    0    0    0    0]
 [   0    0    0 1689    0    0 3000    0    0    0    0 1689]
 [   0    0    0    0  537    0    0    0    0  952    0    0]
 [   0    0    0    0    0 1268    0    0  715    0 1268    0]
 [   0    0    0    0    0    0    0    0    0  952    0 1689]
 [   0    0    0    0    0    0    0 2251    0    0 1268    0]]


In [7]:
def route(local_start, local_end):
    route = [local_start]
    next_location = local_start
    while (next_location != local_end):
            starting_state = location_to_state[local_start]
            next_state = np.argmax(Q[starting_state])
            next_location = state_to_location[next_state]
            route.append(next_location)
            local_start = next_location
    return route


In [8]:
print(f"Rota: {route('E','G')}")

Rota: ['E', 'I', 'J', 'F', 'B', 'C', 'G']
